ingredient_enrichment_task:
  description: >
    Based on the {{ingredients}} provided by the user, the chef agent should come up with interesting dish from a certain country, recommend additional ingredients 
    that will elevate the dish while respecting its cultural context. And come with a interesting a catching story about why he chose this dish and what the dish represents.
  expected_output: >
    A name of the dish
    A reason why he chose this dish
    A captivating backstory about the recipe’s cultural significance
    A list of additional recommended ingredients that will enhance the dish without overshadowing the core i{{ingredients}}.
  agent: chef_agent

recipe_instruction_task:
  description: >
    Create a clear, step-by-step recipe based on the chef's ingredients and recommendations. 
    The recipe should be well-structured and easy to follow for all skill levels.
  expected_output: >
    A recipe formatted with a bullet-point list of ingredients followed by simple, numbered cooking steps.
  agent: recipe_agent

music_and_culture_recommendation_task:
  description: >
    Find a niche music track from the country of origin of the recipe and share an interesting fact about the band or artist. 
    Suggest the song as ideal cooking music to accompany the preparation of the dish.
  expected_output: >
    A song recommendation along with an interesting tidbit about the band or artist from the recipe's country of origin.
  agent: music_aficionado
